# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160503_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default=datetime.datetime(2016, 5, 3, 12, 43, 35, 844356, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
