# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='class_of_article',
            field=models.CharField(choices=[('LF', 'life'), ('PY', 'python')], default='LF', max_length=2),
        ),
    ]
